[package]
name = "krypter"
version = "1.0.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
image = "0.25.6"
rand = "0.9.1"
